<script>
/* Supabase falso en memoria para pruebas locales */
window.__R={errors:[],alerts:[],checks:[],log:[]};
window.addEventListener('error',e=>{__R.errors.push({page:(typeof page!=='undefined'?page:''),msg:e.message,src:(e.filename||'')+':'+e.lineno,stack:(e.error&&e.error.stack||'').split('\n').slice(0,3).join(' | ')})});
window.addEventListener('unhandledrejection',e=>{__R.errors.push({page:(typeof page!=='undefined'?page:''),msg:'PROMISE: '+(e.reason&&e.reason.message||e.reason),stack:(e.reason&&e.reason.stack||'').split('\n').slice(0,3).join(' | ')})});
window.print=()=>{__R.log.push('print bloqueado en '+(typeof page!=='undefined'?page:''))};window.open=()=>null;
window.alert=m=>{__R.alerts.push({page:(typeof page!=='undefined'?page:''),msg:String(m)})};window.confirm=()=>true;window.prompt=()=>'';
const DB={perfiles:[{id:'u1',email:'prueba@tempo.local',rol:'admin',nombre:'Usuario de prueba',area:null}]};
const tabla=t=>DB[t]=DB[t]||[];
window.__W={writes:[],deny:null,silencio:null,seq:0};window.__RPC={falta:false,error:null,ultimo:null,ultimoPri:null,n:0};window.__AUTH={reset:null,updated:null,cb:null,err:null}; // registro de escrituras y rechazo simulado de la base (RLS)
function builder(t){const st={t,op:'select',filters:[],single:false,payload:null,ids:null};
  const b={select(){return b},order(k,o){st.order=String(k||"");st.desc=!!(o&&o.ascending===false);return b},range(a,c){st.range=[a,c];return b},limit(n){st.limit=n;return b},eq(k,v){st.filters.push([k,v]);return b},single(){st.single=true;return b},
    upsert(rows){st.op='upsert';st.payload=rows;return b},delete(){st.op='delete';return b},in(k,ids){st.ids=ids;return b},update(obj){st.op='update';st.payload=obj;return b},
    then(res,rej){let rows=tabla(t);try{
      if(st.op==='select'){let out=rows.filter(r=>st.filters.every(([k,v])=>r[k]===v));if(st.order)out=out.slice().sort((x,y)=>(String(x[st.order]||"")<String(y[st.order]||"")?-1:1)*(st.desc?-1:1));if(st.single){return res(out.length?{data:out[0],error:null}:{data:null,error:{message:'no rows'}})}
        /* como PostgREST: como máximo 1000 filas por consulta (o el range/limit pedido) */
        if(st.range)out=out.slice(st.range[0],st.range[1]+1);else if(st.limit!=null)out=out.slice(0,st.limit);else out=out.slice(0,1000);
        return res({data:JSON.parse(JSON.stringify(out)),error:null})}
      if(st.op==='upsert'){__W.writes.push({t,op:'upsert',n:(st.payload||[]).length});if(__W.deny&&__W.deny(t,'upsert'))return res({data:null,error:{message:'new row violates row-level security policy for table "'+t+'"'}});(st.payload||[]).forEach(r=>{const i=rows.findIndex(x=>x.id===r.id);const c=JSON.parse(JSON.stringify(r));c.actualizado=new Date(Date.now()+(++__W.seq)).toISOString();if(i<0)rows.push(c);else rows[i]=c});return res({data:null,error:null})}
      if(st.op==='delete'){__W.writes.push({t,op:'delete',n:(st.ids||[]).length});if(__W.deny&&__W.deny(t,'delete'))return res({data:null,error:{message:'permission denied for table '+t}});if(__W.silencio&&__W.silencio(t))return res({data:null,error:null});/* RLS sin política DELETE: 204 y no borra */DB[t]=rows.filter(r=>!(st.ids||[]).includes(r.id));return res({data:null,error:null})}
      if(st.op==='update'){rows.filter(r=>st.filters.every(([k,v])=>r[k]===v)).forEach(r=>Object.assign(r,st.payload));return res({data:null,error:null})}
    }catch(e){return res({data:null,error:{message:e.message}})}}};return b}
window.supabase={createClient(){const user={id:'u1',email:'prueba@tempo.local'};return{auth:{getSession:async()=>({data:{session:{user}}}),onAuthStateChange(cb){__AUTH.cb=cb;return{data:{subscription:{unsubscribe(){}}}}},resetPasswordForEmail:async(email,opts)=>{__AUTH.reset={email,opts};return{data:{},error:null}},updateUser:async(attrs)=>{__AUTH.updated=attrs;return __AUTH.err?{data:null,error:{message:__AUTH.err}}:{data:{user},error:null}},signInWithPassword:async()=>({data:{user},error:null}),signOut:async()=>{}},from:builder,__DB:DB,rpc:async(fn,args)=>{__RPC.n++;__W.writes.push({t:'rpc:'+fn,op:'rpc'});if(__RPC.falta)return{data:null,error:{message:'Could not find the function public.'+fn+' in the schema cache'}};if(__RPC.error)return{data:null,error:{message:__RPC.error}};if(fn==="mover_fase"){const row=(DB.ordenes||[]).find(r=>r.id===args.p_orden);if(!row)return{data:null,error:{message:"orden no existe"}};const antes=(row.data||{}).fase;row.data=row.data||{};row.data.fase=args.p_fase;row.data.fases=(row.data.fases||[]).concat([{f:args.p_fase,antes,ts:new Date().toISOString(),u:"rpc",origen:"manual",motivo:args.p_motivo||""}]);tabla("bitacora").push({id:"b"+Math.random().toString(36).slice(2),data:{ts:new Date().toISOString(),u:"rpc",t:"Fase "+(row.data.op||args.p_orden)+": "+(antes||"-")+" → "+args.p_fase}});row.actualizado=new Date(Date.now()+(++__W.seq)).toISOString();__RPC.ultimo={orden:args.p_orden,antes,despues:args.p_fase,motivo:args.p_motivo||""};return{data:{ok:true},error:null}}if(fn==="set_prioridad_centro"){const row=(DB.ordenes||[]).find(r=>r.id===args.p_orden);if(!row)return{data:null,error:{message:"orden no existe"}};row.data=row.data||{};row.data.progCentro=row.data.progCentro||{};row.data.progCentro[args.p_centro]=row.data.progCentro[args.p_centro]||{};if(args.p_pri)row.data.progCentro[args.p_centro].pri=args.p_pri;else delete row.data.progCentro[args.p_centro].pri;row.actualizado=new Date(Date.now()+(++__W.seq)).toISOString();__RPC.ultimoPri={orden:args.p_orden,centro:args.p_centro,pri:args.p_pri};return{data:{ok:true},error:null}}return{data:null,error:null}},storage:{__FILES:{},__BLOBS:{},from(b){const F=this.__FILES;const B=this.__BLOBS;return{async upload(p,blob,o){if(F[b+"/"+p]!=null&&!(o&&o.upsert))return{data:null,error:{message:"The resource already exists"}};F[b+"/"+p]=blob?blob.size:0;B[b+"/"+p]=blob;return{data:{path:p},error:null}},async download(p){const bl=B[b+"/"+p];if(bl==null)return{data:null,error:{message:"Object not found"}};return{data:bl,error:null}},async list(pref,o){const lim=(o&&o.limit)||100;return{data:Object.keys(F).filter(k=>k.startsWith(b+"/"+(pref||""))).slice(0,lim).map(k=>({name:k.slice(b.length+1)})),error:null}},getPublicUrl(p){return{data:{publicUrl:"https://mock/storage/v1/object/public/"+b+"/"+p}}}}}}}}};
</script>
