<script>
/* Supabase falso en memoria para pruebas locales */
window.__R={errors:[],alerts:[],checks:[],log:[]};
window.addEventListener('error',e=>{__R.errors.push({page:(typeof page!=='undefined'?page:''),msg:e.message,src:(e.filename||'')+':'+e.lineno,stack:(e.error&&e.error.stack||'').split('\n').slice(0,3).join(' | ')})});
window.addEventListener('unhandledrejection',e=>{__R.errors.push({page:(typeof page!=='undefined'?page:''),msg:'PROMISE: '+(e.reason&&e.reason.message||e.reason),stack:(e.reason&&e.reason.stack||'').split('\n').slice(0,3).join(' | ')})});
window.print=()=>{__R.log.push('print bloqueado en '+(typeof page!=='undefined'?page:''))};window.open=()=>null;
window.alert=m=>{__R.alerts.push({page:(typeof page!=='undefined'?page:''),msg:String(m)})};window.confirm=()=>true;window.prompt=()=>'';
const DB={perfiles:[{id:'u1',email:'prueba@tempo.local',rol:'admin',nombre:'Usuario de prueba',area:null}]};
const tabla=t=>DB[t]=DB[t]||[];
window.__W={writes:[],deny:null};window.__RPC={falta:false,error:null,ultimo:null,n:0}; // registro de escrituras y rechazo simulado de la base (RLS)
function builder(t){const st={t,op:'select',filters:[],single:false,payload:null,ids:null};
  const b={select(){return b},order(){return b},range(){return b},limit(){return b},eq(k,v){st.filters.push([k,v]);return b},single(){st.single=true;return b},
    upsert(rows){st.op='upsert';st.payload=rows;return b},delete(){st.op='delete';return b},in(k,ids){st.ids=ids;return b},update(obj){st.op='update';st.payload=obj;return b},
    then(res,rej){let rows=tabla(t);try{
      if(st.op==='select'){let out=rows.filter(r=>st.filters.every(([k,v])=>r[k]===v));if(st.single){return res(out.length?{data:out[0],error:null}:{data:null,error:{message:'no rows'}})}return res({data:JSON.parse(JSON.stringify(out)),error:null})}
      if(st.op==='upsert'){__W.writes.push({t,op:'upsert',n:(st.payload||[]).length});if(__W.deny&&__W.deny(t))return res({data:null,error:{message:'new row violates row-level security policy for table "'+t+'"'}});(st.payload||[]).forEach(r=>{const i=rows.findIndex(x=>x.id===r.id);const c=JSON.parse(JSON.stringify(r));if(i<0)rows.push(c);else rows[i]=c});return res({data:null,error:null})}
      if(st.op==='delete'){__W.writes.push({t,op:'delete',n:(st.ids||[]).length});if(__W.deny&&__W.deny(t))return res({data:null,error:{message:'permission denied for table '+t}});DB[t]=rows.filter(r=>!(st.ids||[]).includes(r.id));return res({data:null,error:null})}
      if(st.op==='update'){rows.filter(r=>st.filters.every(([k,v])=>r[k]===v)).forEach(r=>Object.assign(r,st.payload));return res({data:null,error:null})}
    }catch(e){return res({data:null,error:{message:e.message}})}}};return b}
window.supabase={createClient(){const user={id:'u1',email:'prueba@tempo.local'};return{auth:{getSession:async()=>({data:{session:{user}}}),onAuthStateChange(){},signInWithPassword:async()=>({data:{user},error:null}),signOut:async()=>{}},from:builder,__DB:DB,rpc:async(fn,args)=>{__RPC.n++;__W.writes.push({t:'rpc:'+fn,op:'rpc'});if(__RPC.falta)return{data:null,error:{message:'Could not find the function public.'+fn+' in the schema cache'}};if(__RPC.error)return{data:null,error:{message:__RPC.error}};if(fn==="mover_fase"){const row=(DB.ordenes||[]).find(r=>r.id===args.p_orden);if(!row)return{data:null,error:{message:"orden no existe"}};const antes=(row.data||{}).fase;row.data=row.data||{};row.data.fase=args.p_fase;row.data.fases=(row.data.fases||[]).concat([{f:args.p_fase,antes,ts:new Date().toISOString(),u:"rpc",origen:"manual",motivo:args.p_motivo||""}]);tabla("bitacora").push({id:"b"+Math.random().toString(36).slice(2),data:{ts:new Date().toISOString(),u:"rpc",t:"Fase "+(row.data.op||args.p_orden)+": "+(antes||"-")+" → "+args.p_fase}});__RPC.ultimo={orden:args.p_orden,antes,despues:args.p_fase,motivo:args.p_motivo||""};return{data:{ok:true},error:null}}return{data:null,error:null}},storage:{__FILES:{},from(b){const F=this.__FILES;return{async upload(p,blob,o){F[b+"/"+p]=blob?blob.size:0;return{data:{path:p},error:null}},async list(){return{data:Object.keys(F).map(k=>({name:k})),error:null}},getPublicUrl(p){return{data:{publicUrl:"https://mock/storage/v1/object/public/"+b+"/"+p}}}}}}}}};
</script>
