/* Arma los dos Excel de la usuaria con estilo (XLSXB). Correr en ?captura=audit después de cargar xlsx_build.js. */
async function armarTiempos(){await XLSXB.cargarExcelJS();const n2=x=>x==null||x===''?'':Math.round(x*100)/100;const hijas=S.categorias.filter(k=>k.padre);const ords=S.ordenes.filter(o=>abierta(o)&&lanzada(o));
  const CEN=['corte','estampado','sublimado','apliques','bordado','modulos','botones','etiquetas','lavado','cordones','plancha','empaque'].filter(c=>CE(c));
  const rowsC=hijas.map(k=>{const os=ords.filter(o=>o.cat===k.id);const spc=samPorCentro(k)||{};const t={};CEN.forEach(c=>{t[c]=+((tiempoPaso({centro:c,t:0},k,spc,0)||{}).t)||0});const enRuta={};CEN.forEach(c=>{enRuta[c]=os.filter(o=>((o.rutaCompleta||[]).concat(o.ruta||[])).some(p=>p.centro===c)).length});return {k,fam:(K(k.padre)||{}).n,hija:k.n,n:os.length,hoja:tieneHojaLMO(k),t,enRuta,ob:ojalBotonDe(k)}});
  const bot=rowsC.filter(r=>r.t.botones===0&&(r.enRuta.botones>0||r.ob)).map(r=>{const ops=(opsDe(r.k)||[]).filter(x=>x.centro==='botones');const lmoT=ops.reduce((a,x)=>a+(+x.sam||0),0);const causa=!r.hoja?'la familia no tiene hoja de operaciones':(r.ob&&ops.length?'la tabla de ojales y botones dice 0 y manda sobre la hoja':(r.ob&&!ops.length?'la tabla tiene valor pero la hoja no trae la operación: no se aplica':'sin fila en la tabla y sin operación en la hoja'));
    return {'Familia':r.fam,'Tipo de producto':r.hija,'Órdenes con Botones en la ruta':r.enRuta.botones,'Tabla ojales y botones (hoy)':r.ob?n2(r.ob.ojales)+' + '+n2(r.ob.botones):'(sin fila)','Hoja LMO (suma botones)':ops.length?n2(lmoT):'(ninguna)','Por qué está en 0':causa,'Ojales + botones REAL (min/prenda)':'','Observación':''}});
  const sinHoja=rowsC.filter(r=>!r.hoja).map(r=>({'Familia':r.fam,'Tipo de producto':r.hija,'Órdenes lanzadas':r.n,'Corte hoy':0,'Confección hoy':r.k.minEstConf?n2(r.k.minEstConf)+' (estimado)':'estimado de Santiago (16-sep)','Empaque hoy':0,'Corte REAL (min/prenda)':'','Confección REAL (min/prenda)':'','Empaque REAL (min/prenda)':'','Observación':''}));
  const nuevos=[{'Paso':'Sublimado','Dónde va':'después de Estampado','Cómo entra a la ruta':'solo, cuando la técnica de la orden dice sublimado; o a mano','Hoy':'0 min/prenda','Qué falta':'minuto por prenda (o por técnica / tipo de producto)'},{'Paso':'Apliques','Dónde va':'después de Estampado','Cómo entra a la ruta':'solo, cuando la técnica dice aplique; o a mano','Hoy':'0 min/prenda','Qué falta':'minuto por prenda'},{'Paso':'Cordones','Dónde va':'terminados, antes de Plancha','Cómo entra a la ruta':'a mano','Hoy':'0 min/prenda','Qué falta':'minuto por prenda (pasar cordón)'},{'Paso':'Calandrado','Dónde va':'antes de Corte (tela cruda que se estampa afuera)','Cómo entra a la ruta':'a mano','Hoy':'0 días de espera','Qué falta':'DÍAS que tarda (plazo del proveedor)'}].map(x=>Object.assign(x,{'Valor REAL':'','Observación':''}));
  const opsTipo=[];hijas.filter(k=>tieneHojaLMO(k)).sort((a,b)=>((K(a.padre)||{}).n||'').localeCompare((K(b.padre)||{}).n||'')||a.n.localeCompare(b.n)).forEach(k=>{const ops=opsDe(k).slice().sort((a,b)=>ordenPaso(a.centro)-ordenPaso(b.centro)||((OP(a.op)||{}).sec||0)-((OP(b.op)||{}).sec||0));const codes={};ops.forEach(x=>{const c=(OP(x.op)||{}).cod||x.n;codes[c]=(codes[c]||0)+1});
    ops.forEach(x=>{const o=OP(x.op)||{};opsTipo.push({'Familia':(K(k.padre)||{}).n,'Tipo de producto':k.n,'Centro':nCen(x.centro),'Sección':o.seccOp||'','Familia de operación':o.famOp||'','Operación':x.n,'Código':o.cod||'','Máquina':x.maq||'','SAM (min)':n2(x.sam),'Variante (mismo código, otra máquina)':codes[o.cod]>1?'sí':'','¿Aplica a este tipo?':'','SAM real si cambia':''})})});
  const resumen=hijas.filter(k=>tieneHojaLMO(k)).map(k=>{const spc=samPorCentro(k)||{};const ops=opsDe(k);return {'Familia':(K(k.padre)||{}).n,'Tipo de producto':k.n,'Operaciones que suma hoy':ops.length,'Confección hoy (min/prenda)':n2(spc.modulos||0),'Corte':n2(spc.corte||0),'Empaque':n2(spc.empaque||0),'Cómo se calcula hoy':'suma de TODAS las operaciones de la hoja de la familia (fijas y variantes)'}});
  const wb=new ExcelJS.Workbook();wb.creator='TEMPO PCP';
  XLSXB.portada(wb,'Tiempos: solo lo que falta (TEMPO PCP · 20-sep-2026)',[
    ['Qué es esto','Solo lo que falta por poner tiempos en el sistema. Llena las celdas AMARILLAS y devuelve el mismo archivo; el resto no se toca.'],
    ['Hoja «Botones (faltan)»','Tipos de producto cuyo paso Botones hoy entra en 0. Escribe ojales + botones reales en min/prenda (o 0 si no lleva). Jeans y Vestidos: la tabla dice 0 y manda sobre la hoja.'],
    ['Hoja «Sin hoja»','11 familias sin hoja de operaciones: corte y empaque en 0, confección estimada. Llenar las tres columnas REAL.'],
    ['Hoja «Pasos nuevos»','Sublimado, Apliques, Cordones (minutos por prenda) y Calandrado (días de plazo).'],
    ['Hoja «Resumen por tipo»','Cómo calcula hoy el sistema el tiempo estándar: suma TODAS las operaciones de la hoja de la familia, fijas y variantes, y da lo mismo a todos los tipos de la familia (las 11 camisetas = 13,46 min de confección). Por eso la hoja siguiente.'],
    ['Hoja «Operaciones por tipo»','Una fila por operación y tipo de producto. En «¿Aplica a este tipo?» elige SÍ o NO (p. ej. «Pegar bolsillo» solo en Camiseta Bolsillo; de dos máquinas para la misma operación, una). Con eso el sistema suma solo lo que aplica a cada tipo. Si el SAM cambia, escríbelo en «SAM real si cambia».'],
    ['Ejemplo','Camiseta CV · Pegar tirilla · TIRILLADORA 0,42 → ¿Aplica? SÍ · Camiseta CV · Pegar tirilla · RECTA DOBLE AGUJA 0,55 → ¿Aplica? NO (la misma operación en otra máquina: se marca una sola)']]);
  XLSXB.hoja(wb,'Botones (faltan)',[{k:'Familia',w:16},{k:'Tipo de producto',w:22},{k:'Órdenes con Botones en la ruta',w:14,num:true},{k:'Tabla ojales y botones (hoy)',w:16},{k:'Hoja LMO (suma botones)',w:14},{k:'Por qué está en 0',w:44,wrap:true},{k:'Ojales + botones REAL (min/prenda)',w:22,llenar:true},{k:'Observación',w:34,llenar:true,wrap:true}],bot,{titulo:'Botones: tipos de producto que hoy entran en 0',banda:'Familia'});
  XLSXB.hoja(wb,'Sin hoja',[{k:'Familia',w:18},{k:'Tipo de producto',w:22},{k:'Órdenes lanzadas',w:12,num:true},{k:'Corte hoy',w:10,num:true},{k:'Confección hoy',w:24},{k:'Empaque hoy',w:11,num:true},{k:'Corte REAL (min/prenda)',w:16,llenar:true},{k:'Confección REAL (min/prenda)',w:18,llenar:true},{k:'Empaque REAL (min/prenda)',w:16,llenar:true},{k:'Observación',w:34,llenar:true,wrap:true}],sinHoja,{titulo:'Familias sin hoja de operaciones: corte, confección y empaque',banda:'Familia'});
  XLSXB.hoja(wb,'Pasos nuevos',[{k:'Paso',w:14},{k:'Dónde va',w:30,wrap:true},{k:'Cómo entra a la ruta',w:40,wrap:true},{k:'Hoy',w:14},{k:'Qué falta',w:34,wrap:true},{k:'Valor REAL',w:16,llenar:true},{k:'Observación',w:34,llenar:true,wrap:true}],nuevos,{titulo:'Pasos de ruta nuevos: minutos por prenda (Calandrado: días)'});
  XLSXB.hoja(wb,'Resumen por tipo',[{k:'Familia',w:16},{k:'Tipo de producto',w:22},{k:'Operaciones que suma hoy',w:12,num:true},{k:'Confección hoy (min/prenda)',w:14,num:true},{k:'Corte',w:9,num:true},{k:'Empaque',w:9,num:true},{k:'Cómo se calcula hoy',w:60,wrap:true}],resumen,{titulo:'Cómo calcula hoy el sistema el tiempo estándar (solo lectura)',nota:'Solo información: aquí no hay nada que llenar. Lo que aplica a cada tipo se marca en la hoja «Operaciones por tipo».',banda:'Familia'});
  XLSXB.hoja(wb,'Operaciones por tipo',[{k:'Familia',w:14},{k:'Tipo de producto',w:20},{k:'Centro',w:12},{k:'Sección',w:14},{k:'Familia de operación',w:16},{k:'Operación',w:34,wrap:true},{k:'Código',w:10},{k:'Máquina',w:22},{k:'SAM (min)',w:9,num:true},{k:'Variante (mismo código, otra máquina)',w:12},{k:'¿Aplica a este tipo?',w:14,llenar:true,lista:['SÍ','NO']},{k:'SAM real si cambia',w:12,llenar:true}],opsTipo,{titulo:'Operaciones por tipo de producto: marca SÍ / NO en «¿Aplica a este tipo?»',nota:'Una fila por operación y tipo. Amarillo = para llenar (elige SÍ o NO de la lista). «Variante» = la misma operación con otra máquina: marca SÍ en una sola.',banda:o=>o['Familia']+'  ›  '+o['Tipo de producto']});
  return {saved:await XLSXB.guardar(wb,'TIEMPOS_SOLO_LO_QUE_FALTA.xlsx'),bot:bot.length,sinHoja:sinHoja.length,opsTipo:opsTipo.length,resumen:resumen.length}}

async function armarPropuesta(){await XLSXB.cargarExcelJS();const rows=await (await fetch('/propuesta_rows.json')).json();
  const S3=rows.filter(o=>/^3 /.test(o['Sección'])&&o['Hoy se llama']!=null),S3b=rows.filter(o=>/^3 /.test(o['Sección'])&&o['Hoy']!=null),S4=rows.filter(o=>/^4 /.test(o['Sección'])),S6=rows.filter(o=>/^6 /.test(o['Sección'])),otras=rows.filter(o=>!/^[346] /.test(o['Sección']));
  const DEC='Tu decisión (OK · NO · cambiar a…)';const dec={k:DEC,w:18,llenar:true,lista:['OK','NO','Cambiar a…']},com={k:'Comentario',w:40,llenar:true,wrap:true};
  const wb=new ExcelJS.Workbook();wb.creator='TEMPO PCP';
  XLSXB.portada(wb,'Propuesta de Configuración «para dummies»: para tachar (20-sep-2026)',[
    ['Qué es esto','Las tablas de la propuesta CONFIGURACION_PARA_DUMMIES_PROPUESTA.md, una fila por elemento, con dos columnas amarillas para ti: «Tu decisión» (OK · NO · Cambiar a…) y «Comentario». Nada está construido: primero se tacha, después se hace.'],
    ['Hoja «Para tachar (estructura)»','Una fila por elemento de Configuración: cómo se llama hoy, cómo se llamaría, en qué pestaña/cajón queda y por qué. Las filas gris-azuladas son las pestañas nuevas (Mi planta · Reglas · Productos y tiempos · Personas y permisos · Administrador).'],
    ['Hoja «Diccionario»','Palabras técnicas de hoy y cómo se verían en planta. Tacha las que no te gusten y escribe la tuya en Comentario.'],
    ['Hoja «Qué sale de Configuración»','Lo que se saca de Configuración y a dónde va (p. ej. personas por centro a Planificar el mes).'],
    ['Hoja «Riesgos»','Qué podría salir mal al reordenar y cómo se cuida.'],
    ['Hoja «Otras tablas»','El inventario de hoy, los tres diseños que se compararon y tu idea para la nivelación.'],
    ['Cómo devolverlo','Llena solo las celdas amarillas (o mándame capturas con lo tachado). Con eso arranco el paso 1: mover y renombrar, sin cambiar ningún cálculo.']]);
  XLSXB.hoja(wb,'Para tachar (estructura)',[{k:'Hoy se llama',w:34,wrap:true},{k:'Se llamará',w:34,wrap:true},{k:'Dónde queda',w:26,wrap:true},{k:'Por qué',w:44,wrap:true},dec,com],S3,{titulo:'La estructura nueva, pantalla por pantalla',banda:'Bloque',notaAlta:false});
  XLSXB.hoja(wb,'Diccionario',[{k:'Técnico (hoy)',w:30,wrap:true},{k:'Planta (se verá)',w:34,wrap:true},{k:'Por qué',w:44,wrap:true},dec,com],S4,{titulo:'Diccionario de palabras (solo textos visibles)',banda:'Bloque'});
  XLSXB.hoja(wb,'Qué sale de Configuración',[{k:'Hoy',w:36,wrap:true},{k:'Va a',w:36,wrap:true},{k:'Por qué',w:44,wrap:true},dec,com],S3b,{titulo:'Lo que sale de Configuración y a dónde va'});
  XLSXB.hoja(wb,'Riesgos',[{k:'#',w:5},{k:'Riesgo',w:44,wrap:true},{k:'Cómo se cuida',w:52,wrap:true},dec,com],S6,{titulo:'Riesgos y cómo se cuidan'});
  const otrasCols=[{k:'Sección',w:26,wrap:true},{k:'Bloque',w:22,wrap:true}];const keysO=[...new Set(otras.flatMap(o=>Object.keys(o)))].filter(k=>!['Sección','Bloque',DEC,'Comentario'].includes(k));keysO.forEach(k=>otrasCols.push({k,w:30,wrap:true}));otrasCols.push(dec,com);
  XLSXB.hoja(wb,'Otras tablas',otrasCols,otras,{titulo:'Inventario de hoy, diseños comparados y tu idea para la nivelación',banda:'Sección'});
  return {saved:await XLSXB.guardar(wb,'PROPUESTA_CONFIGURACION_PARA_TACHAR.xlsx'),n:rows.length,S3:S3.length,S4:S4.length,S3b:S3b.length,S6:S6.length,otras:otras.length}}
window.armarTiempos=armarTiempos;window.armarPropuesta=armarPropuesta;
